name: nlp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ipykernel
  - seaborn
  - flake8
  - pip
  - pip:
    - scikit-learn
    - numpy
    - nltk
    - tqdm
    - pandas
    - seaborn
    